let _  = require('lodash');
let fs = require('fs');
let list_all = [{
	"tee_time": "08:00",
	"tee_date": "2021-03-31",
	"pay_time": null,
	"created_at": "2021-03-11 16:34:08",
	"deleted_at": null,
	"updated_at": "2021-03-11 16:34:10",
	"id": "195",
	"parentid": "193",
	"booking_sn": "B2103115964892405614",
	"fieldid": "12",
	"booking_source": "be_union",
	"cell": null,
	"uid": "9468",
	"user_type": "common",
	"fullname": "司淑蕊",
	"mobile": "13876871046",
	"member_sn": null,
	"usercardid": null,
	"userrightid": null,
	"price": 1,
	"total_addition_fee": 0,
	"total_addition_desc": null,
	"total_price": 0,
	"hole_type": "18",
	"status": 4,
	"creator_id": null,
	"channelid": null,
	"start_course": null,
	"contact": null,
	"extra": null,
	"remark": null,
	"pay_name": "线上",
	"payTradeNo": null,
	"pay_status": true,
	"clearing_status": 0,
	"clearing_operator_uid": null,
	"refund_status": 0,
	"User": {
		"created_at": "2021-03-08 21:40:43",
		"deleted_at": null,
		"updated_at": "2021-03-09 14:28:25",
		"id": "9468",
		"fullname": "司淑蕊",
		"nickname": "司淑蕊Rachel",
		"gender": 2,
		"mobile": "13876871046",
		"password": null,
		"status": true,
		"headimg": "https://thirdwx.qlogo.cn/mmopen/vi_32/oXudqhU3yGN0SKujYow1vW0cekAMZV5nYibNe0tib1ANfqALN5jfPwf8MibBV6DlxMbXeiaucax2ChQnGsl6yQFm1Q/132",
		"corpid": null,
		"vip": null,
		"extra": null,
		"remark": null,
		"username": null,
		"is_expired": false,
		"creator_id": null
	},
	"Field": {
		"created_at": "2021-02-20 10:30:48",
		"deleted_at": null,
		"updated_at": null,
		"id": "12",
		"name": "重庆上邦温泉高尔夫俱乐部",
		"name_en": "Chongqing Sun Kingdom Golf Club",
		"short_name": "重庆上邦",
		"province": "重庆",
		"city": "重庆",
		"description": "作为重庆环境最优美的球场，上邦拥有无可比似的原生态自然环境：三万亩缙云山脉原始森林造就了天然氧吧，空气清新怡人；著名度假胜地海兰云天景色秀美，如一幅巴山蜀水的水墨丹青。在缙云山脉与海兰湖畔的山水之间，山林葱葱、湖光倒影、白鹭飞翔、鸟语花香是上邦独有的自然风光，秀美的景色让球友们在挥杆之余贴近自然，充分感受到高尔夫与大自然的完美融合，感受到“山、水、林、泉”溶入高尔夫的那份神韵。在上邦高尔夫俱乐部，您既可以品尝中西美味佳肴，体验一流的赛事活动，享受最优质的尊贵服务，更能纵情欣赏一番缙云山的美景，享受挥杆后的自然情趣。",
		"director": "鲁黎丽",
		"mobile": "023-65748888/65742355",
		"phone": "023-65748888/65742355",
		"fax": "023-65741555",
		"address_zh": "重庆市九龙坡区金凤镇上邦国际社区",
		"address_en": null,
		"operating_company_name_zh": null,
		"operating_company_name_en": null,
		"type": "union",
		"status": 1,
		"creatorid": null,
		"creator_mobile": null,
		"hole_min": null,
		"min_spacing": null,
		"opening_area": null,
		"hole_set": null,
		"headimg": "/golf_field/12_cqsb_1.jpg",
		"photos": "/golf_field/12_cqsb_1.jpg,/golf_field/12_cqsb_2.jpg,/golf_field/12_cqsb_3.jpg",
		"logo": "/golf_field/12_cqsb_logo.jpg",
		"remark": null,
		"setting": null,
		"offseason_time_range": "",
		"highseason_time_range": ""
	},
	"Creator": null
}, {
	"tee_time": "08:00",
	"tee_date": "2021-03-31",
	"pay_time": null,
	"created_at": "2021-03-11 16:33:55",
	"deleted_at": null,
	"updated_at": "2021-03-11 16:34:10",
	"id": "194",
	"parentid": "193",
	"booking_sn": "B2103115963577813482",
	"fieldid": "12",
	"booking_source": "be_union",
	"cell": null,
	"uid": "9452",
	"user_type": "card",
	"fullname": "罗心晶",
	"mobile": "13911353511",
	"member_sn": "KL000010",
	"usercardid": "23",
	"userrightid": "887",
	"price": 1,
	"total_addition_fee": 0,
	"total_addition_desc": null,
	"total_price": 0,
	"hole_type": "18",
	"status": 2,
	"creator_id": null,
	"channelid": null,
	"start_course": null,
	"contact": null,
	"extra": null,
	"remark": null,
	"pay_name": "线上",
	"payTradeNo": null,
	"pay_status": false,
	"clearing_status": 0,
	"clearing_operator_uid": null,
	"refund_status": 0,
	"User": {
		"created_at": "2021-03-07 11:01:07",
		"deleted_at": null,
		"updated_at": "2021-03-07 11:45:07",
		"id": "9452",
		"fullname": "罗心晶",
		"nickname": "水晶",
		"gender": 2,
		"mobile": "13911353511",
		"password": null,
		"status": true,
		"headimg": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLc1ISPcytA2y8a2Qedv3ic3WP3rliaWbILjZZGUYZb2yZxZia1nDcrds9SLYgPw3pSuI3O8jG2X4e6A/132",
		"corpid": null,
		"vip": null,
		"extra": null,
		"remark": null,
		"username": null,
		"is_expired": false,
		"creator_id": "1"
	},
	"Field": {
		"created_at": "2021-02-20 10:30:48",
		"deleted_at": null,
		"updated_at": null,
		"id": "12",
		"name": "重庆上邦温泉高尔夫俱乐部",
		"name_en": "Chongqing Sun Kingdom Golf Club",
		"short_name": "重庆上邦",
		"province": "重庆",
		"city": "重庆",
		"description": "作为重庆环境最优美的球场，上邦拥有无可比似的原生态自然环境：三万亩缙云山脉原始森林造就了天然氧吧，空气清新怡人；著名度假胜地海兰云天景色秀美，如一幅巴山蜀水的水墨丹青。在缙云山脉与海兰湖畔的山水之间，山林葱葱、湖光倒影、白鹭飞翔、鸟语花香是上邦独有的自然风光，秀美的景色让球友们在挥杆之余贴近自然，充分感受到高尔夫与大自然的完美融合，感受到“山、水、林、泉”溶入高尔夫的那份神韵。在上邦高尔夫俱乐部，您既可以品尝中西美味佳肴，体验一流的赛事活动，享受最优质的尊贵服务，更能纵情欣赏一番缙云山的美景，享受挥杆后的自然情趣。",
		"director": "鲁黎丽",
		"mobile": "023-65748888/65742355",
		"phone": "023-65748888/65742355",
		"fax": "023-65741555",
		"address_zh": "重庆市九龙坡区金凤镇上邦国际社区",
		"address_en": null,
		"operating_company_name_zh": null,
		"operating_company_name_en": null,
		"type": "union",
		"status": 1,
		"creatorid": null,
		"creator_mobile": null,
		"hole_min": null,
		"min_spacing": null,
		"opening_area": null,
		"hole_set": null,
		"headimg": "/golf_field/12_cqsb_1.jpg",
		"photos": "/golf_field/12_cqsb_1.jpg,/golf_field/12_cqsb_2.jpg,/golf_field/12_cqsb_3.jpg",
		"logo": "/golf_field/12_cqsb_logo.jpg",
		"remark": null,
		"setting": null,
		"offseason_time_range": "",
		"highseason_time_range": ""
	},
	"Creator": null
}, {
	"tee_time": "08:00",
	"tee_date": "2021-03-31",
	"pay_time": null,
	"created_at": "2021-03-11 16:33:47",
	"deleted_at": null,
	"updated_at": "2021-03-11 16:34:10",
	"id": "193",
	"parentid": null,
	"booking_sn": "B2103115962745050739",
	"fieldid": "12",
	"booking_source": "be_union",
	"cell": null,
	"uid": "9483",
	"user_type": "common",
	"fullname": "孙启静 ",
	"mobile": "15612116717",
	"member_sn": null,
	"usercardid": null,
	"userrightid": null,
	"price": 1,
	"total_addition_fee": 10,
	"total_addition_desc": "手续费",
	"total_price": 13,
	"hole_type": "18",
	"status": 2,
	"creator_id": null,
	"channelid": null,
	"start_course": null,
	"contact": null,
	"extra": null,
	"remark": "这是一个多人订单",
	"pay_name": "线上",
	"payTradeNo": null,
	"pay_status": false,
	"clearing_status": 0,
	"clearing_operator_uid": null,
	"refund_status": 0,
	"User": {
		"created_at": "2021-03-11 16:22:53",
		"deleted_at": null,
		"updated_at": "2021-03-11 16:24:57",
		"id": "9483",
		"fullname": "孙启静 ",
		"nickname": "孙启静 Priscilla",
		"gender": 2,
		"mobile": "15612116717",
		"password": null,
		"status": true,
		"headimg": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKNueO5SvcgZM7DrbfiaCeNTtpVcEWGJ8NjSkPbzHN1C8xDcrZ56r6co1FNibaDU2xnFic72G2YNxOGw/132",
		"corpid": null,
		"vip": null,
		"extra": null,
		"remark": null,
		"username": null,
		"is_expired": false,
		"creator_id": null
	},
	"Field": {
		"created_at": "2021-02-20 10:30:48",
		"deleted_at": null,
		"updated_at": null,
		"id": "12",
		"name": "重庆上邦温泉高尔夫俱乐部",
		"name_en": "Chongqing Sun Kingdom Golf Club",
		"short_name": "重庆上邦",
		"province": "重庆",
		"city": "重庆",
		"description": "作为重庆环境最优美的球场，上邦拥有无可比似的原生态自然环境：三万亩缙云山脉原始森林造就了天然氧吧，空气清新怡人；著名度假胜地海兰云天景色秀美，如一幅巴山蜀水的水墨丹青。在缙云山脉与海兰湖畔的山水之间，山林葱葱、湖光倒影、白鹭飞翔、鸟语花香是上邦独有的自然风光，秀美的景色让球友们在挥杆之余贴近自然，充分感受到高尔夫与大自然的完美融合，感受到“山、水、林、泉”溶入高尔夫的那份神韵。在上邦高尔夫俱乐部，您既可以品尝中西美味佳肴，体验一流的赛事活动，享受最优质的尊贵服务，更能纵情欣赏一番缙云山的美景，享受挥杆后的自然情趣。",
		"director": "鲁黎丽",
		"mobile": "023-65748888/65742355",
		"phone": "023-65748888/65742355",
		"fax": "023-65741555",
		"address_zh": "重庆市九龙坡区金凤镇上邦国际社区",
		"address_en": null,
		"operating_company_name_zh": null,
		"operating_company_name_en": null,
		"type": "union",
		"status": 1,
		"creatorid": null,
		"creator_mobile": null,
		"hole_min": null,
		"min_spacing": null,
		"opening_area": null,
		"hole_set": null,
		"headimg": "/golf_field/12_cqsb_1.jpg",
		"photos": "/golf_field/12_cqsb_1.jpg,/golf_field/12_cqsb_2.jpg,/golf_field/12_cqsb_3.jpg",
		"logo": "/golf_field/12_cqsb_logo.jpg",
		"remark": null,
		"setting": null,
		"offseason_time_range": "",
		"highseason_time_range": ""
	},
	"Creator": null,
	"Children": [{
		"tee_time": "08:00",
		"tee_date": "2021-03-31",
		"pay_time": null,
		"created_at": "2021-03-11 16:33:55",
		"deleted_at": null,
		"updated_at": "2021-03-11 16:34:10",
		"id": "194",
		"parentid": "193",
		"booking_sn": "B2103115963577813482",
		"fieldid": "12",
		"booking_source": "be_union",
		"cell": null,
		"uid": "9452",
		"user_type": "card",
		"fullname": "罗心晶",
		"mobile": "13911353511",
		"member_sn": "KL000010",
		"usercardid": "23",
		"userrightid": "887",
		"price": 1,
		"total_addition_fee": 0,
		"total_addition_desc": null,
		"total_price": 0,
		"hole_type": "18",
		"status": 2,
		"creator_id": null,
		"channelid": null,
		"start_course": null,
		"contact": null,
		"extra": null,
		"remark": null,
		"pay_name": "线上",
		"payTradeNo": null,
		"pay_status": false,
		"clearing_status": 0,
		"clearing_operator_uid": null,
		"refund_status": 0
	}, {
		"tee_time": "08:00",
		"tee_date": "2021-03-31",
		"pay_time": null,
		"created_at": "2021-03-11 16:34:08",
		"deleted_at": null,
		"updated_at": "2021-03-11 16:34:10",
		"id": "195",
		"parentid": "193",
		"booking_sn": "B2103115964892405614",
		"fieldid": "12",
		"booking_source": "be_union",
		"cell": null,
		"uid": "9468",
		"user_type": "common",
		"fullname": "司淑蕊",
		"mobile": "13876871046",
		"member_sn": null,
		"usercardid": null,
		"userrightid": null,
		"price": 1,
		"total_addition_fee": 0,
		"total_addition_desc": null,
		"total_price": 0,
		"hole_type": "18",
		"status": 2,
		"creator_id": null,
		"channelid": null,
		"start_course": null,
		"contact": null,
		"extra": null,
		"remark": null,
		"pay_name": "线上",
		"payTradeNo": null,
		"pay_status": false,
		"clearing_status": 0,
		"clearing_operator_uid": null,
		"refund_status": 0
	}]
}]

let final_result = {
    list:list_all
}

let tempalte_str = fs.readFileSync('./bookinglist.html', 'utf8');
let compiled = _.template(tempalte_str);
let result = compiled(final_result);

console.log('result', result);
fs.writeFileSync('./result.html', Buffer.from(result))